applications:

  - name: "Maya 2025"
    department: "Modeling / Rigging / Animation / Layout"
    icon: icons\dcc\maya.png
    environment:
      - name: "Maya 2025 + Renderman 26.3"
        rez_package: maya_software-2025 renderman_maya_plugin-26.3
        command: maya
      - name: "Maya 2025 + MtoA 5.5.2.0 (Core 7.4.2.0)"
        rez_package: maya_software-2025 arnold_maya_plugin-5.5.2.0
        command: maya

  - name: "3dsmax 2023"
    department: "Modeling / Rigging / Animation / Layout"
    icon: icons\dcc\3dsmax.ico
    environment:
      - name: "3dsmax 2023"
        rez_package: 3dsmax_software-2023
        command: 3dsmax
  
  - name: "3dsmax 2025"
    department: "Modeling / Rigging / Animation / Layout"
    icon: icons\dcc\3dsmax.ico
    environment:
     - name: "3dsmax 2025"
       rez_package: 3dsmax_software-2025
       command: 3dsmax

  - name: "Houdini 20.5"
    department: "CFX / FX / Environment"
    icon: icons\dcc\houdini.ico
    environment:
      - name: "Houdini Core 20.5.445"
        rez_package: houdini_software-20.5.445
        command: houdinicore
      - name: "Houdini FX 20.5.445"
        rez_package: houdini_software-20.5.445
        command: houdinifx

  - name: "Gaffer 1.5"
    department: "Assembly / LookDev / Lighting"
    icon: icons\dcc\gaffer.png
    environment:
      - name: "Gaffer 1.5.14.0 + Renderman 26.3"
        rez_package: gaffer_software-1.5.14.0 renderman_gaffer_plugin-26.3
        command: gaffer
      - name: "Gaffer 1.5.14.0 + Arnold 7.2.0"
        rez_package: gaffer_software-1.5.14.0 arnold_core_plugin-7.4.2.0
        command: gaffer
      - name: "Gaffer 1.5.14.0 + Arnold Core 7.4.2.0 + Renderman 26.3"
        rez_package: gaffer_software-1.5.14.0 arnold_core_plugin-7.4.2.0 renderman_gaffer_plugin-26.3
        command: gaffer

      - name: "Gaffer 1.5.15.0 + Renderman 26.3"
        rez_package: gaffer_software-1.5.15.0 renderman_gaffer_plugin-26.3
        command: gaffer
      - name: "Gaffer 1.5.15.0 + Arnold 7.2.0"
        rez_package: gaffer_software-1.5.15.0 arnold_core_plugin-7.4.2.0
        command: gaffer
      - name: "Gaffer 1.5.15.0 + Arnold Core 7.4.2.0 + Renderman 26.3"
        rez_package: gaffer_software-1.5.15.0 arnold_core_plugin-7.4.2.0 renderman_gaffer_plugin-26.3
        command: gaffer
  
  - name: "Nuke 15.2v1"
    department: "Compositing / Editing / Review"
    icon: icons\dcc\nuke.png
    environment:
      - name: "Nuke 15.2v1 Non-Commercial"
        rez_package: nuke_software-15.2.1
        command: nuke15.2 --nc
      - name: "NukeStudio 15.2v1 Non-Commercial"
        rez_package: nuke_software-15.2.1
        command: nuke15.2 --studio --nc
      - name: "NukeX 15.2v1 Non-Commercial"
        rez_package: nuke_software-15.2.1
        command: nuke15.2 --nukex --nc
  
  - name: "Hiero 15.2v1"
    department: "Compositing / Editing / Review"
    icon: icons\dcc\hiero.png
    environment:
      - name: "Hiero 15.2v1"
        rez_package: nuke_software-15.2.1
        command: nuke15.2 --hiero
      - name: "Hiero Player 15.2v1"
        rez_package: nuke_software-15.2.1
        command: nuke15.2 --player
  
  - name: "OpenRV 1.0"
    department: "Compositing / Editing / Review"
    icon: icons\dcc\openrv.png
    environment:
      - name: "OpenRV 1.0"
        rez_package: openrv_software
        command: rv.exe

  - name: "Syntheyes 2024"
    department: "Compositing / Editing / Review"
    icon: icons\dcc\syntheyes.png
    environment:
      - name: "Syntheyes 2024"
        rez_package: syntheyes_software-2024
        command: syntheyes

  - name: "Mari 7.0v1"
    department: "Texturing"
    icon: icons\dcc\mari.png
    environment:
      - name: "Mari 7.0v1 Non-Commercial" 
        rez_package: mari_software-7.0.1
        command: Mari7.0v1 --nc -platform windows:nowmpointer
      - name: "Mari 7.0v1"
        rez_package: mari_software-7.0.1
        command: Mari7.0v1 -platform windows:nowmpointer

  - name: "Adobe Substance 3D Painter 11.0.1"
    department: "Texturing"
    icon: icons\dcc\painter.png
    environment:
      - name: "Adobe Substance 3D Painter 11.0.1"
        rez_package: substancePainter_software-11.0.1
        command: 'Adobe Substance 3D Painter'